package diary.appointment.model;


import java.util.UUID;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

//import org.joda.time.DateTime;
//import org.apache.commons.text.StringEscapeUtils;
import diary.appointment.config.Config;

@DynamoDBTable(tableName=Config.DYNAMODB_TABLE_NAME)


//MAIN CLASS WHERE ENTITIES HAVE BEEN DEFINED 
public class Appointment{
	
	public UUID id;
	
	public long dateTime;
	
	public int duration;
	
	public String owner;
	
	public String description; 
	

	public Appointment() {
		
	}
	
	//CONSTRUCTOR
	
	public Appointment(UUID id, String owner, long dateTime, int duration, String description)
	{
		if (id != null) {
			this.setId( id);
		}
		else {
			this.setId( UUID.randomUUID());
		
		}
		this.setDateTime(dateTime);
		this.setOwner( owner);
				
		this.setDescription(description);
		
		this.setDuration(duration);
		
	}//end method



	@DynamoDBHashKey(attributeName="id")
	@DynamoDBAutoGeneratedKey
	public UUID getId() {
		return id;
	}




	public void setId(UUID id) {
		this.id = id;
	}



	@DynamoDBAttribute(attributeName="dateTime")
	public long getDateTime() {
		return dateTime;
	}




	public void setDateTime(long dateTime) {
		this.dateTime = dateTime;
	}



	@DynamoDBAttribute(attributeName="duration")

	public int getDuration() {
		return duration;
	}




	public void setDuration(int duration) {
		this.duration = duration;
	}



	@DynamoDBAttribute(attributeName="owner")

	public String getOwner() {
		return owner;
	}




	public void setOwner(String owner) {
		this.owner = owner;
	}



	@DynamoDBAttribute(attributeName="description")
	public String getDescription() {
		return description;
	}




	public void setDescription(String description) {
		this.description = description;
	}




	public String toXml() {
		String result = "<Appointment ";
		result += "id=\"" + this.id+"\" ";
		result += "dateTime=\""+this.dateTime+"\"";
		result+="duration=\""+this.duration+"\" ";  
		result+="owner=\""+this.owner+"\" "; 
		result+="description=\""+this.description+"\" ";  
		//result+="description=\""+StringEscapeUtils.escapeXml10(this.description)+"\" />"; 
		return result;
	
	}



	@Override
	public String toString() {
		return "Appointment [id=" + id + ", dateTime=" + dateTime + ", duration=" + duration + ", owner=" + owner
				+ ", description=" + description + "]";
	}









	
	
	
	
	
	

	
	

}
